name: build-multiarch-dev

on:
  pull_request:
    branches:
    - v20.04

jobs:
  push:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    strategy:
      fail-fast: false
      matrix:
        image:
          - { platforms: "linux/amd64,linux/arm64/v8,linux/arm/v7" }

    steps:
      - uses: actions/checkout@v2

      - name: Set up QEMU (conditionally)
        uses: docker/setup-qemu-action@v1
        if: ${{ matrix.image.platforms != 'linux/amd64' }}

      - name: Install buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Determine variables
        run: |
          IMAGE_ID=ghcr.io/${{ github.repository }}
          echo "IMAGE_ID=${IMAGE_ID}" >> $GITHUB_ENV
          VERSION=$(echo "${{ github.base_ref }}" | sed -e 's/^v//')-dev
          echo "VERSION=${VERSION}" >> $GITHUB_ENV

      - name: Build and Push
        uses: docker/build-push-action@v2
        with:
          platforms: ${{ matrix.image.platforms }}
          push: true
          tags: ${{ env.IMAGE_ID }}:${{ env.VERSION }}
